### ISSUE TITLE
error on calling .flatness() method

### ISSUE THREAD

**Issue by dheathar** [jsawruk/pymir#6]
Hi,
i am using pimyr library and i had the following error

Traceback (most recent call last):
  File "/Users/panayiotis/PycharmProjects/MirFramework/mirFramework.py", line 106, in <module>
    flatness_SFeat.append(m.flatness())
  File "/Library/Python/2.7/site-packages/pymir/Spectrum.py", line 116, in flatness
    geometricMean = scipy.stats.mstats.gmean(abs(self),axis=0)
  File "/Library/Python/2.7/site-packages/scipy/stats/stats.py", line 508, in gmean
    return np.exp(log_a.mean(axis=axis))
TypeError: mean() got an unexpected keyword argument 'axis'

on the following function

```
    flatness_SFeat = [m.flatness() for m in spectra]                # Spectral Flatness
```

where spectra is calculated from the following
        spectra = [f.spectrum() for f in fixedFrames]

any idea?

**Comment by hihell** [comment]
I have the same problem, fixed by following (in Spectrum.py):
`
asArray = self.view(numpy.ndarray)
        geometricMean = scipy.stats.mstats.gmean(abs(asArray), axis=0)
`

you need to translate type spectrum back to numpy array to make it work

**Comment by dheathar** [comment]
I will try it! 
Thanks for replying!!!
